const Laptops = [
  {
    _id: 1,
    name: 'Asus VivoBook S15 M513UA Ryzen 7 5700U 15.6" FHD Laptop',
    description:
      "The Asus VivoBook S15 M513UA Laptop comes with AMD Ryzen 7 5700U (8MB L3 cache, 1.8GHz Up to 4.3GHz), 8GB DDR4 RAM, 512GB M.2 NVMe PCI-E G3.0 SSD, AMD Radeon Graphics and Windows 11 64-Bit Operating System. This laptop featured with 15.6-inch, FHD (1920 x 1080) 16:9, IPS-level Panel, Anti-glare display, LED Backlit, 300nits, sRGB: 100%, Screen-to-body ratio: 86 50WHrs, 3S1P, 3-cell Li-ion Battery, Built-in speaker Built-in array microphone Harman/Kardon (Mainstream) with Cortana and Alexa voice-recognition support, Illuminated Backlit Chiclet Keyboard with Num-key 1.4mm Key-travel and HD WebCam. Here, Wi-Fi 6(802.11ax)+ (Dual-band) 2 x 2 and Bluetooth 5.0. Here, Wi-Fi 6(802.11ax)+ (Dual-band) 2 x 2 and Bluetooth 5.0 are also available. This laptop also has 1x USB 3.2 Gen 1 Type-A , 1x USB 3.2 Gen 1 Type-C, 2 x USB 2.0 Type-A, 1 x HDMI 1.4, 1 x 3.5mm Combo Audio Jack, 1x DC-in Micro SD card reader. The latest Asus VivoBook S15 M513UA Laptop has 02 years International Limited Warranty (Battery 1 year).",
    price: 573,
    MPN: "BQ648W",
    Model: "VivoBook S15 M513UA",
    Processor: "AMD Ryzen 7 5700U (8MB L3 cache, 1.8GHz Up to 4.3GHz)",
    RAM: "8GB RAM, Storage: 512GB SSD",
    Display: '15.6" FHD (1920 x 1080) IPS',
    url: "https://i.ibb.co/n7yvNcC/no-1.jpg",
  },
  {
    _id: 2,
    name: 'Doel Freedom A9 AMD A9-9425 14.1" HD Laptop',
    description:
      'The Doel Freedom A9 is a 14.1" laptop from Doel. It is the first laptop made in Bangladesh. The Doel Freedom A9 is powered by an AMD A9-9425 processor (1MB Cache, 3.10GHz up to 3.70GHz). The AMD A9-9425 is an entry-level chip from the Stoney-Ridge APU series for notebooks. It has a 100 MHz higher CPU clock speed (base and boost) as well as a marginally faster GPU. It integrates two CPU cores (one Excavator module with 2 integers and an FP unit) clocked at 3.1 GHz to 3.7 GHz. It also includes a Radeon R5 GPU with 192 shaders at up to 900 MHz as well as a single-channel DDR4-2133 memory controller. The Doel Freedom A9 comes with 4GB DDR4 RAM and a 240GB SATAIII M.2 SSD. It is integrated with AMD Radeon R5 Graphics and has a 14.1-inch HD (1366x768) Matte LED-backlit display with 45% NTSC. This laptop runs on Windows 10 operating system. The Doel Freedom A9 offers a 1-year warranty.',
    price: 519,
    MPN: "BQ648W",
    Model: "VivoBook S15 M513UA",
    Processor: "AMD Ryzen 7 5700U (8MB L3 cache, 1.8GHz Up to 4.3GHz)",
    RAM: "8GB RAM, Storage: 512GB SSD",
    Display: '15.6" FHD (1920 x 1080) IPS',
    url: "https://i.ibb.co/VCL041T/no-2.jpg",
  },
  {
    _id: 3,
    name: 'AVITA Essential 14 Celeron N4020 256GB SSD 14" Full HD Laptop Concrete Grey Color',
    description:
      'AVITA Essential 14 Celeron N4020 14" Full HD Laptop come with Intel Celeron Processor N4020 (4M Cache, 1.10 GHz up to 2.80 GHz), 4GB LPDDR4 RAM, 256GB SATA M.2 SSD, Intel UHD Graphics 600 with Windows 10 Home in S mode. This laptop is featured with Battery: 7.6V 4830mAh, Island style non-backlit keyboard, 2M WebCam, Micro SD card, 14" FHD (1920 x 1080) IPS Display, 0.8W x 2 Speaker, Dual Microphones. Here, Network & Wireless Connectivity are also available. In this laptop it is also has USB 3.0 Type-A x 2, Full size HDMI x 1, Headphone Jack Ports, Connectors & Slots are also availble. This latest AVITA Essential 14 Celeron N4020 14" Full HD Laptop has 2 Years of Warranty.',
    price: 525,
    MPN: "BQ648W",
    Model: "Freedom A9",
    Processor: "AMD A9-9425 (1MB Cache, 3.10GHz up to 3.70GHz)",
    RAM: "4GB DDR4 RAM, Storage: 240GB SATAIII M.2 SSD",
    Display: '14.1" HD (1366x768)',
    url: "https://i.ibb.co/cQJBNBh/no-4.jpg",
  },
  {
    _id: 4,
    name: 'AVITA Essential 14 Celeron N4020 256GB SSD 14" Full HD Laptop Matt White Color',
    description:
      'AVITA Essential 14 Celeron N4020 14" Full HD Laptop come with Intel Celeron Processor N4020 (4M Cache, 1.10 GHz up to 2.80 GHz), 4GB LPDDR4 RAM, 256GB SATA M.2 SSD, Intel UHD Graphics 600 with Windows 10 Home in S mode. This laptop is featured with Battery: 7.6V 4830mAh, Island style non-backlit keyboard, 2M WebCam, Micro SD card, 14" FHD (1920 x 1080) IPS Display, 0.8W x 2 Speaker, Dual Microphones. Here, Network & Wireless Connectivity are also available. In this laptop it is also has USB 3.0 Type-A x 2, Full size HDMI x 1, Headphone Jack Ports, Connectors & Slots are also availble. This latest AVITA Essential 14 Celeron N4020 14" Full HD Laptop has 2 Years of Warranty.',
    price: 741,
    MPN: "NE14A2BDC44A-CRB",
    Model: "Essential 14",
    Processor: "Intel Celeron Processor N4020 (4M Cache, 1.10 GHz up to 2.80 GHz)",
    RAM: "4GB LPDDR4 RAM 256GB SATA M.2 SSD",
    Display: '14" FHD (1920 x 1080) IPS Display',
    url: "https://i.ibb.co/mHzMLJX/no-6.jpg",
  },
  {
    _id: 5,
    name: 'Walton Prelude N5000A Pentium N5000 14" HD Laptop',
    description:
      'The Walton Prelude N5000A Laptop Comes with Intel Pentium Silver N5000 Processor (4M Cache, 1.10 GHz up to 2.70 GHz), 4GB Dual Channel DDR4 RAM. It also has a 256GB SATAIII M.2 2280 SSD. This laptop comes with a 14" HD (1366x768) Display. It also features Intel UHD Graphics 605, Dynamic frequency, Intel Dynamic Video Memory Technology, and Microsoft DirectX 12 compatibility. Here, High definition audio, Built-in array microphone, Built-in two speakers, 1 x USB 2.0 port, 1 x USB 3.0 (USB3.1 Gen 1) port (Type A), 1 x USB 3.0 (USB3.1 Gen 1) port (Type C), 1 x external VGA port, 1 x HDMI output port (with HDCP), 1 x Headphone Jack, 1 x Microphone jack, 1 x RJ-45 LAN port and 1 x DC-in jacks are available. This new laptop also comes with a Built-in 10/100/1000Mb Base-TX Ethernet LAN, 802.11ac WLAN, Bluetooth 4.2, 1.0M HD video camera. The Walton Prelude N5000A Laptop comes with 2 years of Warranty (Battery Adapter 1 year).',
    price: 939,
    MPN: "NE14A2BDC44A-MWB",
    Model: "AVITA Essential 14",
    Processor: "Intel Celeron Processor N4020 (4M Cache, 1.10 GHz up to 2.80 GHz)",
    RAM: "4GB LPDDR4 RAM 256GB SATA M.2 SSD",
    Display: '14" FHD (1920 x 1080) IPS Display',
    url: "https://i.ibb.co/r68Ch94/no-12.jpg",
  },
  {
    _id: 6,
    name: "Torphy-Vandervort",
    description:
      'AVITA Essential 14 Celeron N4020 14" Full HD Laptop come with Intel Celeron Processor N4020 (4M Cache, 1.10 GHz up to 2.80 GHz), 4GB LPDDR4 RAM, 256GB SATA M.2 SSD, Intel UHD Graphics 600 with Windows 10 Home in S mode. This laptop is featured with Battery: 7.6V 4830mAh,  Island style non-backlit keyboard, 2M WebCam, Micro SD card, 14" FHD (1920 x 1080) IPS Display, 0.8W x 2 Speaker, Dual Microphones. Here, Network & Wireless Connectivity are also available. In this laptop it is also has USB 3.0 Type-A x 2, Full size HDMI x 1, Headphone Jack Ports, Connectors & Slots are also availble. This latest AVITA Essential 14 Celeron N4020 14" Full HD Laptop has 2 Years of Warranty.',
    price: 738,
    MPN: "N5000A",
    Model: "Prelude N5000A",
    Processor: "Intel Pentium Silver N5000 (4M Cache, 1.10 GHz, up to 2.70 GHz)",
    RAM: "4GB 2400MHz RAM, Storage: 256GB SATAIII M.2 2280 SSD",
    Display: '14.0" HD (1366X768)',
    url: "https://i.ibb.co/cv3DXkN/no-10.jpg",
  },
  {
    _id: 7,
    name: "Nienow, Kuhn and Simonis",
    description:
      "The Lenovo IdeaPad Slim 3i Laptop comes with Intel Celeron N4020 Processor (4M Cache,1.10 GHz up to 2.80 GHz), 4GB DDR4 2400Mhz RAM, 1TB 5400rpm HDD, Intel UHD Graphics 600, and Windows 10 Home operating system. This laptop is also featured with a 2 Cell Li-Polymer battery, Full-size English (US) keyboard, 720p HD Webcam with Privacy Shutter, an SD card reader. Here, WiFi 2 x 2, 1 x 1 AC and Bluetooth Version 5.0 Network & Wireless Connectivity are available. In this laptop, it has 2 x USB 3.1 (Gen 1)USB 2.0, HDMI 1.4b, Headphone / mic combo, 2 x 1.5W speakers Dolby Audio Ports, Connectors & Slots and Finger Print Sensor. The Lenovo IdeaPad Slim 3i Laptop has 02 years International Limited Warranty (Terms & condition Apply As Per Lenovo).",
    price: 838,
    MPN: "NE14A2BDC44A-MBB",
    Model: "AVITA Essential 14",
    Processor: "Intel Celeron Processor N4020 (4M Cache, 1.10 GHz up to 2.80 GHz)",
    RAM: "4GB LPDDR4 RAM 256GB SATA M.2 SSD",
    Display: '14" FHD (1920 x 1080) IPS Display',
    url: "https://i.ibb.co/YDdx79f/no-7.jpg",
  },
  {
    _id: 8,
    name: "Murazik, Effertz and Ernser",
    description:
      "Dell Inspiron 15 3510 comes with Intel Celeron Dual Core N4020 (4MB Cache, 1.10 GHz Up To 2.80 GHz) Processor and Intel UHD Graphics 600. This Dell Inspiron 15 3510 featured 4GB DDR4 2400MHz, 1TB 5400RPM SATA HDD, that will provide you with responsive and stable performance. It is also designed with 15.6-inch HD (1366x768) Anti-Glare LED Backlight Narrow Border Display. This Dell Inspiron 15 3510 laptop will give you an excellent experience of lightning-fast responsiveness and hyper-efficient battery life that keeps you productive with a 4-Cell Battery, 54WHr (Integrated) battery. The Dell Inspiron 15 3510 Laptop has Pointing Device, Touchpad Keyboard with Numeric Keypad, an English US, an HD camera, Dual-array microphones. All-new Dell Inspiron 15 3510 Laptop has a mechanical camera shutter that protects against anyone invading your privacy or accidental embarrassments on video calls; so you can read, watch, or chat and attend any meeting, presentation or Conference also. The latest Dell Inspiron 15 3510 Laptop offers 2 Years Warranty (Battery & Adapter 01 Year).",
    price: 909,
    MPN: "BQ648W",
    Model: "VivoBook S15 M513UA",
    Processor: "AMD Ryzen 7 5700U (8MB L3 cache, 1.8GHz Up to 4.3GHz)",
    RAM: "8GB RAM, Storage: 512GB SSD",
    Display: '15.6" FHD (1920 x 1080) IPS',
    url: "https://i.ibb.co/ZJBgLTW/no-9.jpg",
  },
  {
    _id: 9,
    name: "Ritchie and Sons",
    description:
      'The Lenovo IdeaPad Slim 3i 15IGL comes with Intel Celeron N4020 (4M Cache, 1.10 GHz up to 2.80 GHz) and 4GB DDR4 2400MHz RAM. It also comes with a 1TB 5400rpm 2.5" HDD to store all your important data. It is integrated with Integrated Intel UHD Graphics 600 and it has a 15.6" HD (1366 x 768) display with TN panel and 220nits Anti-glare screen. This laptop is powered by an Integrated 35Wh battery and it has a 45W Round Tip (2-pin, Wall-mount) adapter. The Lenovo IdeaPad Slim 3i 15IGL features Firmware TPM 2.0 and it runs on the Windows 11 Home operating system. It has a 720p camera with Privacy Shutter. It has been designed with 1x Power connector, 1x 4-in-1 Card Reader, 1x HDMI 1.4b, 1x Headphone/microphone combo jack (3.5mm), 1x USB 2.0 and 2x USB 3.2 Gen 1. Lenovo IdeaPad Slim 3i 15IGL offers High Definition (HD) Audio, Stereo speakers, 1.5W x2, Dolby Audio and 2x, Array Microphone. This laptop comes in Platinum Grey color. The Lenovo IdeaPad Slim 3i 15IGL comes with 2 years of warranty.',
    price: 590,
    MPN: "81WQ00BUIN",
    Model: "IdeaPad Slim 3i",
    Processor: "Intel Celeron N4020 Processor (4M Cache,1.10 GHz up to 2.80 GHz)",
    RAM: "4GB DDR4 2400Mhz RAM 512GB SSD 1TB 5400rpm HDD",
    Display: '15.6"HD (1366x768) Display',
    url: "https://i.ibb.co/Pr7k2jY/no-8.jpg",
  },
];

export default Laptops;
